services:
  - type: web
    name: brain-tumor-api
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && echo 'Downloading model...' && python download_model.py && echo 'Model download completed'
    startCommand: bash -c 'sleep 10 && echo "Starting API after model download" && uvicorn main:app --host 0.0.0.0 --port $PORT'
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
